project:
  type: website

website:
  title: "Albert MBUA"
  navbar:
    background: secondary
    style: "floating"
    search: true
    right:
      - text: Home
        file: index.qmd
      - text: About
        file: about.qmd
      - sidebar:apuntes_helsinki
      - sidebar:devops

    sidebar:
      - id: "apuntes_helsinki"
        title: "apuntes_helsinki" 
        border: true
        collapse-level: 1
        background: none
        style: "floating"
        contents: 
          - text: "apuntes_helsinki"
          - text: "---"  
          - section: "apuntes_helsinki: "
            contents: 
              - apuntes_helsinki/part1.qmd
              - apuntes_helsinki/part2.qmd
            




format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



