project:
  type: website

website:
  title: "Albert MBUA"
  navbar:
    background: secondary
    style: "floating"
    search: true
    right:
      - text: Home
        file: index.qmd
      - text: About
        file: about.qmd
      - text: Apuntes Helsinki
        file: apuntes_helsinki/part1.qmd
              apuntes_helsinki/part2.qmd
      - text: Definiciones
        file: Definitions/definitions.qmd
      

  sidebar:
    - id: "apuntes_helsinki"
      title: "Apuntes Helsinki" 
      border: true
      collapse-level: 1
      background: none
      style: "floating"
      contents: 
        - text: "---"  
        - section: "Apuntes Helsinki: "
          contents: 
            - apuntes_helsinki/part1.qmd
            - apuntes_helsinki/part2.qmd
        - text: "---"  
    - id: "definitions"
      title: "Definiciones"
      border: true
      collapse-level: 1
      background: none
      style: "floating"
      contents: 
        - text: "---"   
        - section: "Definiciones: "
          contents: 
            - Definitions/definitions.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



